name: blink
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_floating_bottom_bar: ^1.2.0
  simple_circular_progress_bar: ^1.0.2
  page_transition: ^2.1.0
  flutter_svg: ^2.0.10+1
  syncfusion_flutter_charts: ^25.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/blink.svg
